COMMIT: "2ff07a316a512d6dde08370229936984d45d7e67"

env:
  WHOAMI_NAME: "DOGS-v0.0.0"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: "letsencrypt"
    # ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: whoami.dogs.monomi.eu
      paths: ["/"]
  # tls:
  #   - secretName:
  #     hosts:
  #       -
