COMMIT: "a0f495d24fc4104c6d1f459269992f09910bcee9"

env:
  WHOAMI_NAME: "DOGS-v0.0.2"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: "letsencrypt"
    # ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: whoami.dogs.monomi.eu
      paths: ["/"]
  # tls:
  #   - secretName:
  #     hosts:
  #       -
