COMMIT: "ced51b256c4cae44f316775ab5703ef2fc78cdfd"

env:
  WHOAMI_NAME: "DOGS-STAGING-ced51b2"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: "letsencrypt"
    # ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: whoami.staging.dogs.monomi.eu
      paths: ["/"]
  # tls:
  #   - secretName:
  #     hosts:
  #       -
