COMMIT: "e891a0b3345a820773514fa9836c05e0981db0e9"

env:
  WHOAMI_NAME: "DOGS-e891a0b"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: "letsencrypt"
    # ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: whoami.staging.dogs.monomi.eu
      paths: ["/"]
  # tls:
  #   - secretName:
  #     hosts:
  #       -
