COMMIT: "d2d5320d3586d5b5e5736e1c368b77eb3400ea4b"

env:
  WHOAMI_NAME: "DOGS-STAGING-d2d5320"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: "letsencrypt"
    # ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: whoami.staging.dogs.monomi.eu
      paths: ["/"]
  # tls:
  #   - secretName:
  #     hosts:
  #       -
