COMMIT: "v0.0.0"

env:
  WHOAMI_NAME: "CATS-PRODUCTION"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: "letsencrypt"
    # ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: whoami.cats.monomi.eu
      paths: ["/"]
  # tls:
  #   - secretName:
  #     hosts:
  #       -
